version: '3.7'
services:
  app1:
    image: hmatthews/practicalproj-app1
    build: ./app1
    ports:
    - 5000:5000
    environment:
      DATABASE_URI: $DATABASE_URI
      SECRET_KEY: $SECRET_KEY
    depends_on: 
    - app2
    - app3
    - app4
    - mysql
    deploy:
      replicas: 3
  app2:
    image: hmatthews/practicalproj-app2
    build: ./app2
    ports:
    - 5001:5001
    deploy:
      replicas: 3
  app3:
    image: hmatthews/practicalproj-app3
    build: ./app3
    ports:
    - 5002:5002
    deploy:
      replicas: 3
  app4:
    image: hmatthews/practicalproj-app4
    build: ./app4
    ports:
    - 5003:5003
    deploy:
      replicas: 3
  mysql:
    image: hmatthews/practicalproj-mysql
    build: ./db
    ports:
    - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: "tickets_db"
    volumes:
    - type: volume
      source: tickets
      target: /var/lib/mysql
volumes:
  tickets: 
